name: Deploy Heroku
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          ref: 'master'
      - run: git status
      - run: git fetch --prune --unshallow
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: chmod +x gradlew
      - run: ./gradlew bootJar -x test
      - run: heroku plugins:install java
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - run: heroku deploy:jar build/libs/*.jar --app ${HEROKU_APP_NAME}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
