name: Build and Deploy Medixx Application
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Docker Image
        run: ./mvnw -B -P publish package -Ddocker.publishRegistry.username="${{ secrets.DOCKER_USER }}" -Ddocker.publishRegistry.password="${{ secrets.DOCKER_PASSWORD }}"

