name: Build and Deploy Medixx Application
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and Push docker image
        run: ./mvnw -B -Ddocker.registry.email="${{ secrets.DOCKER_EMAIL }}" -Ddocker.registry.username="${{ secrets.DOCKER_USER }}" -Ddocker.registry.password="${{ secrets.DOCKER_TOKEN }}" -P publish package
