name: Build and Deploy Medixx Application
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and Push docker image
        env:
          DOCKER_EMAIL: ${{ secrets.DOCKER_EMAIL }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: ./mvnw -B package -P publish -Ddocker.registry.email="${DOCKER_EMAIL}" -Ddocker.registry.username="${DOCKER_USER}" -Ddocker.registry.password="${DOCKER_TOKEN}"
