name: Build and Deploy Medixx Application
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: ./mvnw -B package -P publish -Ddocker.registry.username=${DOCKER_USER} -Ddocker.registry.password=${DOCKER_TOKEN}
